GET {{host-url}}/product

###

POST {{host-url}}/cart
Content-Type: application/json

{
  "productId": "B0001",
  "quantity": 4
}

###

POST {{host-url}}/login
Content-Type: application/json

{
  "username": "manager1@email.com",
  "password": "123",
  "rem": true
}

###

GET {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

[
]

###

PUT {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

1

###
POST {{host-url}}/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 4,
  "productId": "B0002"
}

###

DELETE {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{host-url}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}

###

PATCH {{host-url}}/order/received/2147483643
Authorization: Bearer {{token}}

###

PATCH {{host-url}}/order/autorized/2147483643
Authorization: Bearer {{token}}

###

PATCH {{host-url}}/order/cancel/2147483643
Authorization: Bearer {{token}}

###

GET {{host-url}}/order/2147483643
Authorization: Bearer {{token}}

###

GET {{host-url}}/profile/manager1@email.com
Authorization: Bearer {{token}}

###

PUT {{host-url}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 11111111,
  "email": "administradorprueba@email.com",
  "password": "1234",
  "name": "administrador prueba",
  "phone": "6789",
  "address": "esta es una prueba",
  "active": false,
  "role": "ROLE_CUSTOMER",
  "authorities": [
    {
      "authority": "ROLE_CUSTOMER"
    }
  ]
}

###

GET {{host-url}}/product/B0003
Content-Type: application/json
Authorization: Bearer {{token}}

###

PUT {{host-url}}/seller/product/B0002/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "B0022",
  "productName": "Prueba",
  "productPrice": 100000,
  "productStock": 200,
  "productDescription": "Esto es una prueba",
  "productIcon": "https://cdn.pixabay.com/photo/2015/03/12/12/43/test-670091_960_720.png",
  "productStatus": 0,
  "categoryType": 1
}

###

POST {{host-url}}/seller/product/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "B0022",
  "productName": "Prueba",
  "productPrice": 100000,
  "productStock": 200,
  "productDescription": "Esto es una prueba",
  "productIcon": "https://cdn.pixabay.com/photo/2015/03/12/12/43/test-670091_960_720.png",
  "productStatus": 0,
  "categoryType": 1
}

###

DELETE {{host-url}}/seller/product/B0002/delete
Content-Type: application/json
Authorization: Bearer {{token}}

###